version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - zenn_network
  python:
    build: ./python
    volumes:
      - ./python:/python
      - /tmp/.X11-unix:/tmp/.X11-unix  # Xサーバーソケットのマウント
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - DISPLAY=unix${DISPLAY}  # DISPLAY変数の設定
    tty: true
    networks:
      - zenn_network
    depends_on:
      - server  # 新しく追加したサーバーコンテナに依存する

  server:
    build: ./python/server  # 新しいサーバーコンテナのビルドパス
    volumes:
      - ./python:/app  # サーバーコードが存在するパスに変更
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5000:5000"  # Flaskがデフォルトで使うポート
    networks:
      - zenn_network

  # chrome_video:
  #   image: selenium/video:ffmpeg-6.1-20231212
  #   volumes:
  #     - ./python/src/module/video:/video  # ローカルのvideoディレクトリをコンテナ内の/videosにマウント
  #     - /tmp/.X11-unix:/tmp/.X11-unix  # Xサーバーソケットのマウント
  #     - "/etc/timezone:/etc/timezone:ro"
  #     - "/etc/localtime:/etc/localtime:ro"
  #   depends_on:
  #     - chrome
  #   environment:
  #     - DISPLAY_CONTAINER_NAME=chrome
  #     - FILE_NAME=chrome_video.mp4

networks:
  zenn_network:
    external: true

  # ffmpeg:
  #   image: jrottenberg/ffmpeg  # 例としてjrottenberg/ffmpegイメージを使用
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw

# version: "3"
# services:
#   chrome:
#     image: selenium/standalone-chrome:latest
#     shm_size: 2gb
#     volumes:
#     - "/etc/timezone:/etc/timezone:ro"
#     - "/etc/localtime:/etc/localtime:ro"
#     ports:
#       - "4444:4444"
#       - "7900:7900"
#     networks:
#       - zenn_network
#   python:
#     build: ./python
#     volumes:
#       - ./python:/python
#       - "/etc/timezone:/etc/timezone:ro"
#       - "/etc/localtime:/etc/localtime:ro"
#     tty: true
#     networks:
#       - zenn_network
# networks:
#   zenn_network:
#     external: true
